//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatFormDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> IdReceiver { get; set; }
        public Nullable<int> IdSender { get; set; }
        public Nullable<int> IdDelete { get; set; }
        public Nullable<bool> DeleteEverywhere { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
